
CREATE DATABASE IF NOT EXISTS magistr_cult CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE magistr_cult;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
